[package]
name = "pg_backup_recovery_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
